name: Setup Environment
description: Setup the environment for QA and build
runs:
  using: "composite"
  steps:
    - name: Set up task tool
      uses: arduino/setup-task@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install python setuptools and wheel
      run: |
          pip3 install --upgrade pip setuptools
          pip3 install --upgrade wheel
          pip3 install --upgrade pathlib
      #run: python -m pip install --upgrade pip setuptools pathlib wheel
      shell: bash
